### ISSUE TITLE
Add wheels for python 3.10

### ISSUE THREAD

**Issue by daswer123** [S95Sedan/Deepspeed-Windows#1]
Hi, thank you for the [instructions](https://github.com/oobabooga/text-generation-webui/issues/4734#issuecomment-1843984142) 
I built deepspeed 11.2 for python 3.10.x under CUDA 11.8 and CUDA 12.1. 

I thought you might be interested in adding these wheels to the release so people can choose between python 3.10 and 3.11

I've uploaded the wheels here and would be glad if you add them to yours :)
https://github.com/daswer123/resemble-enhance-windows/releases/tag/deepspeed

`ds_report`
CUDA 11.8

![image](https://github.com/S95Sedan/Deepspeed-Windows/assets/22278673/dade08e5-1250-4242-b61d-b2143aa3fdae)

CUDA 12.1

![image](https://github.com/S95Sedan/Deepspeed-Windows/assets/22278673/df3eabd8-6b4d-4b5a-8ac7-9fedc509f41f)

**Comment by S95Sedan** [comment]
Cheers, should be added to releases.
