### ISSUE TITLE
Experiencing No module named deepspeed.__main__; 'deepspeed' is a package and cannot be directly executed when called deepspeed

### ISSUE THREAD

**Issue by xingyunjohn1** [S95Sedan/Deepspeed-Windows#2]
my command:`python -m deepspeed -V`
output:
```
[2023-12-26 03:34:00,919] [INFO] [real_accelerator.py:158:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2023-12-26 03:34:01,056] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
D:\anaconda3\envs\cyh-Fuyu\python.exe: No module named deepspeed.__main__; 'deepspeed' is a package and cannot be directly executed
```
I have tried `deepspeed -V`, but only get "Open With" window.
If I open with notepad, I get 
```
#!D:\anaconda3\python.exe

from deepspeed.launcher.runner import main

if __name__ == '__main__':
    main()

```

**Comment by S95Sedan** [comment]
What exactly are you trying to do?

**Comment by xingyunjohn1** [comment]
I am trying to run Fuyu-8b on my 4090 and 3090 So I am using deepspeed. But it seems no command runs correctly after installing your whl. Even the deepspeed -V doesn't work as expected.
Thanks.

**Comment by S95Sedan** [comment]
I think you are trying to use the package in a way it isnt designed to. As from what i can see the -m flag only works if the _ _main_ _; file is present, which isnt the case here.

ds_report should show if its installed and functioning.
Assuming both CUDA_PATH and CUDA_HOME are set correctly.

![image](https://github.com/S95Sedan/Deepspeed-Windows/assets/89262821/dde695bd-9784-4283-87c4-8350bd000b1a)

**Comment by xingyunjohn1** [comment]
I change the command and it work for me now. Using `python deepspeed`.
Thanks a lot.
