### ISSUE TITLE
I am using your DeepSpeed and it is amazing. Can you update Python 3.10 wheels?

### ISSUE THREAD

**Issue by FurkanGozukara** [S95Sedan/Deepspeed-Windows#3]
I am using your DeepSpeed and it is amazing. Can you update Python 3.10 wheels?

Thank you so much

**Comment by S95Sedan** [comment]
The python 3.10 wheels aren't built be me but someone else, as i have everything setup for 3.11 and dont want to break things on my setup.

But with the instructions provided you should be able to make them yourself.

**Comment by FurkanGozukara** [comment]
> The python 3.10 wheels aren't built be me but someone else, as i have everything setup for 3.11 and dont want to break things on my setup.
> 
> But with the instructions provided you should be able to make them yourself.

Who builds 3.10 I will contact him

**Comment by S95Sedan** [comment]
It should say so at the releases.
Also checked and theres wheels there for 3.10.

https://github.com/daswer123/deepspeed-windows-wheels/releases

**Comment by FurkanGozukara** [comment]
> It should say so at the releases. Also checked and theres wheels there for 3.10.
> 
> https://github.com/daswer123/deepspeed-windows-wheels/releases

thank you so much
