### ISSUE TITLE
Just an FYI - Text gen has bumped Pytorch to 2.2.x and DeepSpeed complains.

### ISSUE THREAD

**Issue by erew123** [S95Sedan/Deepspeed-Windows#4]
Hiya!

Hope you are keeping well! :) 

I thought I would let you know, text-gen-webui has bumped its version of PyTorch to 2.2.x https://github.com/oobabooga/text-generation-webui/commit/164ff2440d8a4b05db6671f00df22b83bb49436f and DeepSpeed complains about not being on the correct version. You get messages along the following lines 
```
RuntimeError: PyTorch version mismatch! DeepSpeed ops were compiled and installed with a different version than what is being used at runtime.
Please re-install DeepSpeed or switch torch versions. Install torch version=2.1, Runtime torch version=2.2
```

Im not asking you to do anything about it! I just thought you might want to know (in case you get any messages from anyone).

Ill try get one compiled up soon.

All the best and have a good weekend!

**Comment by S95Sedan** [comment]
The 14.0 release should be updated to reflect the same changes. So it shouldnt complain about a mismatch in versions.

**Comment by erew123** [comment]
Oh, saved me a job there! Thanks. Have a good weekend!

**Comment by S95Sedan** [comment]
No problem, already had it setup for building and using the older one on a new install of Ooba gave me some issues with both gradio and the model giving a still loading error. (which was probably due to he mismatch in version) All thats fixed with this one. 

You have a good weekend too.
