### ISSUE TITLE
made all of the edits still getting error 

### ISSUE THREAD

**Issue by jmanhype** [S95Sedan/Deepspeed-Windows#6]
(videollama2) PS C:\Users\strau\Downloads\DeepSpeed-0.14.0\DeepSpeed-0.14.0> .\build_win.bat
Administrative permissions required. Detecting permissions...
Success: Administrative permissions confirmed.
DS_BUILD_OPS=1
test.c
LINK : fatal error LNK1181: cannot open input file 'aio.lib'
 [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
 [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
Traceback (most recent call last):
  File "C:\Users\strau\Downloads\DeepSpeed-0.14.0\DeepSpeed-0.14.0\setup.py", line 193, in <module>
    ext_modules.append(builder.builder())
                       ^^^^^^^^^^^^^^^^^
  File "C:\Users\strau\Downloads\DeepSpeed-0.14.0\DeepSpeed-0.14.0\op_builder\builder.py", line 633, in builder
    assert_no_cuda_mismatch(self.name)
  File "C:\Users\strau\Downloads\DeepSpeed-0.14.0\DeepSpeed-0.14.0\op_builder\builder.py", line 101, in assert_no_cuda_mismatch
    raise CUDAMismatchException(
op_builder.builder.CUDAMismatchException: >- DeepSpeed Op Builder: Installed CUDA version 12.1 does not match the version torch was compiled with 11.8, unable to compile cuda/cpp extensions without a matching cuda version.
(videollama2) PS C:\Users\strau\Downloads\DeepSpeed-0.14.0\DeepSpeed-0.14.0>

**Comment by S95Sedan** [comment]
You are using the wrong version of torch made for cuda 11.8 instead of 12.1 as seen in the log.

> op_builder.builder.CUDAMismatchException: >- DeepSpeed Op Builder: Installed CUDA version 12.1 does not match the version torch was compiled with 11.8, unable to compile cuda/cpp extensions without a matching cuda version.
